In [171]:
%load_ext autoreload
import numpy as np

In [172]:
# Some Setup
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [173]:
# Create a 3X3 array with uniformly distributed values between 0 and 1
np.random.random((3,3))  

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [174]:
# Create a 3X3 array with normally distributed random values between 0 and 1 with a mean of 0 and std of 1
np.random.normal(0, 1, (3,3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [175]:
# Nested Lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [176]:
# An "empty" array with 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<H1 style="color:CornflowerBlue;">Slicing and Indexing </H1>
<p>arrayName[ith Value]
<p>arrayName[row, column]
<p>arrayName[rowSlice, colSlice]

In [177]:
print(x1)
x1[2]

[5 0 3 3 7 9]


3

In [178]:
print(x2)
x2[0,2]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


2

In [179]:
x = np.arange(10)
print(x)

# The first 5 elements
x[:5]

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4])

In [180]:
# The elements after position 5
x[5:]

array([5, 6, 7, 8, 9])

In [181]:
# Every other element
x[::2]

array([0, 2, 4, 6, 8])

In [182]:
# Reverse the order of the elements
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [183]:
# The first two rows and the first three columns
print(x2)
x2[:2, :3]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([[3, 5, 2],
       [7, 6, 8]])

In [184]:
# Return all of the values in the 3rd column as an array
x2[:, 2]

array([2, 8, 7])

In [185]:
# Return all of the values in the 2nd row
x2[1]

array([7, 6, 8, 8])

<b style="color:CornflowerBlue;"> Reshaping </b> (dimensionality change or tranposition) requires the same number of "cells" between the source and target arrays


In [186]:
grid = np.arange(1, 10).reshape((3,3))  # Note the 2 sets of (())
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [187]:
x = np.array([1,2,3])
print(x.reshape((3,1)))
print(x[np.newaxis, :])
print(x[:, np.newaxis])  # Equivalent to x.reshape((3,1))

[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [188]:
# Setup
x = np.array([1,2,3])
y = np.array([4,5,6])
z = [99, 99, 99]
grid = ([[1, 2, 3],
         [4, 5, 6]])

print(np.concatenate([x,y]))
print(np.concatenate([x,y,z]))
print("Add as new rows")
print(np.concatenate([grid, grid]))
print("Add as new columns")
print(np.concatenate([grid, grid], axis=1))   

[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]
Add as new rows
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Add as new columns
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [189]:
# Split an array (also mutliple assignment)
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


<b style="color:CornflowerBlue;">Broadcasting</b>

In [193]:
# Center an array around 0 (zero)
X = np.random.random((10, 3))
Xmean = X.mean(0)
X_centered = X - Xmean  #Broadcasting happens here
print(X_centered.mean(0))

[ 3.33066907e-17  1.33226763e-16 -2.22044605e-17]


In [200]:
# Broadcasting with Boolean condition matching
x = np.random.RandomState(0).randint(10, size=(3, 4))
print(x)
print(np.count_nonzero(x < 6))

# How many values (as a count) are less than 6 in each row?
print(np.sum(x < 6, axis=1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8
[4 2 2]
