In [1]:
import numpy as np

In [4]:
M = np.ones((2,3))
a = np.arange(3)

print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [6]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)

print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]
